[project]
name = "nixos-discord-bot"
version = "0.2.0"
requires-python = ">=3.11"
dependencies = [
    "discord.py"
]

[project.scripts]
nixos-discord-bot = "nixos_discord_bot.__main__:run"

[tool.pyright]
# Decorated functions marked as unused
reportUnusedFunction = false
